services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
      args:
        - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    platform: linux/amd64
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - api-venv-volumes:/app/.venv
      - api-mypy-cache:/app/.mypy_cache
      - api-ruff-cache:/app/.ruff_cache
    environment:
      - PYTHONPATH=/app
      - MYPYPATH=/app
    command: |
      sh -c "
        poetry install --no-root && \
        poetry run alembic upgrade head && \
        poetry run uvicorn api.app:app --host 0.0.0.0 --port 8888 --reload
      "
    depends_on:
      - db
      - azurite

  jobs:
    build:
      context: ./backend
      dockerfile: ./jobs.Dockerfile.local
      args:
        - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./backend:/app
      - api-venv-volumes:/app/.venv
    environment:
      - PYTHONPATH=/app
      - MYPYPATH=/app
    command: |
      sh -c "
        poetry install --no-root && \
        poetry run python -m scripts.hot_reload
      "
    depends_on:
      - db
      - azurite

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neosmartchat

  function:
    build:
      context: ./function
      dockerfile: ./Dockerfile.local
      args:
        - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    platform: linux/amd64
    working_dir: /app
    volumes:
      - ./function:/app
      - function-venv-volumes:/app/.venv
      - function-mypy-cache:/app/.mypy_cache
      - function-ruff-cache:/app/.ruff_cache
    command: |
      sh -c "
        poetry install --no-root && \
        poetry run python -m scripts.hot_reload
      "
    env_file:
      - ./function/.env
    depends_on:
      - db
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./azurite:/data
    environment:
      - AZURITE_ACCOUNTS="devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;stbloblocal:c3RibG9ibG9jYWw=;stpubliclocal:c3RwdWJsaWNsb2NhbGtleQ==;stbatchlocal:c3RiYXRjaGxvY2Fsa2V5"

  metabase:
    image: metabase/metabase:latest
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
    healthcheck:
      test: curl --fail -I http://localhost:3001/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: postgres

volumes:
  api-venv-volumes:
  function-venv-volumes:
  api-mypy-cache:
  api-ruff-cache:
  function-mypy-cache:
  function-ruff-cache: #a revoir
