import { ModelFamily, Text2ImageModelFamily } from "@/orval/models/backend-api";

export type ModelFamilyDetail = {
  id: ModelFamily | Text2ImageModelFamily;
  name: string;
  accuracy: number | null;
  speed: number | null;
  tokenConsumption: number | string;
  estimatedInputLength: number | null;
  estimatedOutputLength: number | null;
  overview: string;
  tooltip?: string;
};

export const modelNames: { [key in ModelFamily | Text2ImageModelFamily]: string } = {
  [ModelFamily["gpt-35-turbo"]]: "GPT-3.5 Turbo",
  [ModelFamily["gpt-4"]]: "GPT-4",
  [ModelFamily["gpt-4-turbo"]]: "GPT-4 Turbo",
  [ModelFamily["gpt-4o"]]: "GPT-4o",
  [ModelFamily["gpt-4o-mini"]]: "GPT-4o mini",
  [ModelFamily["o1-preview"]]: "o1-preview",
  [ModelFamily["o1-mini"]]: "o1-mini",
  [ModelFamily["claude-3-haiku"]]: "Claude 3 Haiku",
  [ModelFamily["claude-3-sonnet"]]: "Claude 3 Sonnet",
  [ModelFamily["claude-3-opus"]]: "Claude 3 Opus",
  [ModelFamily["claude-35-sonnet"]]: "Claude 3.5 Sonnet",
  [ModelFamily["claude-35-haiku"]]: "Claude 3.5 Haiku",
  [ModelFamily["gemini-15-pro"]]: "Gemini 1.5 Pro",
  [ModelFamily["gemini-10-pro"]]: "Gemini 1.0 Pro",
  [ModelFamily["gemini-15-flash"]]: "Gemini 1.5 Flash",
  [ModelFamily["gemini-20-flash"]]: "Gemini 2.0 Flash",
  [Text2ImageModelFamily["dall-e-3"]]: "DALL·E 3",
};

export const modelFamilyDetails: ModelFamilyDetail[] = [
  {
    id: ModelFamily["gpt-35-turbo"],
    name: modelNames[ModelFamily["gpt-35-turbo"]],
    accuracy: 1,
    speed: 2,
    tokenConsumption: 0.2,
    estimatedInputLength: 12000,
    estimatedOutputLength: 3200,
    overview: "",
  },
  {
    id: ModelFamily["gpt-4"],
    name: modelNames[ModelFamily["gpt-4"]],
    accuracy: 2,
    speed: 1,
    tokenConsumption: 3,
    estimatedInputLength: 6000,
    estimatedOutputLength: 3200,
    overview: "",
  },
  {
    id: ModelFamily["gpt-4-turbo"],
    name: modelNames[ModelFamily["gpt-4-turbo"]],
    accuracy: 3,
    speed: 1,
    tokenConsumption: 1,
    estimatedInputLength: 100000,
    estimatedOutputLength: 3200,
    overview: "海外リージョンの利用が必須。",
  },
  {
    id: ModelFamily["gpt-4o"],
    name: modelNames[ModelFamily["gpt-4o"]],
    accuracy: 3,
    speed: 2,
    tokenConsumption: 0.5,
    estimatedInputLength: 100000,
    estimatedOutputLength: 3200,
    overview: "海外リージョンの利用が必須。",
  },
  {
    id: ModelFamily["gpt-4o-mini"],
    name: modelNames[ModelFamily["gpt-4o-mini"]],
    accuracy: 2,
    speed: 2,
    tokenConsumption: 0,
    estimatedInputLength: 100000,
    estimatedOutputLength: 13000,
    overview: "海外リージョンの利用が必須。",
  },
  {
    id: ModelFamily["o1-preview"],
    name: modelNames[ModelFamily["o1-preview"]],
    accuracy: 3,
    speed: 1,
    tokenConsumption: 5,
    estimatedInputLength: 100000,
    estimatedOutputLength: 26400,
    overview: "海外リージョンの利用が必須。",
    tooltip:
      "OpenAI o1モデルは、複雑な推論を実行可能なモデルで、長い内部思考の連鎖を生成することで精度を高めることができます。思考の連鎖の際のトークン数も計算対象になり、他のモデルと比較して多くのトークン数を消費します。",
  },
  {
    id: ModelFamily["o1-mini"],
    name: modelNames[ModelFamily["o1-mini"]],
    accuracy: 3,
    speed: 1,
    tokenConsumption: 1,
    estimatedInputLength: 100000,
    estimatedOutputLength: 52800,
    overview: "海外リージョンの利用が必須。",
    tooltip:
      "OpenAI o1モデルは、複雑な推論を実行可能なモデルで、長い内部思考の連鎖を生成することで精度を高めることができます。思考の連鎖の際のトークン数も計算対象になり、他のモデルと比較して多くのトークン数を消費します。",
  },
  {
    id: ModelFamily["claude-3-haiku"],
    name: modelNames[ModelFamily["claude-3-haiku"]],
    accuracy: 1,
    speed: 3,
    tokenConsumption: 0.2,
    estimatedInputLength: 160000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["claude-3-sonnet"],
    name: modelNames[ModelFamily["claude-3-sonnet"]],
    accuracy: 1.5,
    speed: 3,
    tokenConsumption: 1.0,
    estimatedInputLength: 160000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["claude-3-opus"],
    name: modelNames[ModelFamily["claude-3-opus"]],
    accuracy: 2.5,
    speed: 2,
    tokenConsumption: 3.0,
    estimatedInputLength: 160000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["claude-35-sonnet"],
    name: modelNames[ModelFamily["claude-35-sonnet"]],
    accuracy: 3,
    speed: 3,
    tokenConsumption: 1.0,
    estimatedInputLength: 160000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["claude-35-haiku"],
    name: modelNames[ModelFamily["claude-35-haiku"]],
    accuracy: 2,
    speed: 3,
    tokenConsumption: 0.5,
    estimatedInputLength: 160000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["gemini-15-pro"],
    name: modelNames[ModelFamily["gemini-15-pro"]],
    accuracy: 3,
    speed: 2,
    tokenConsumption: 0.5,
    estimatedInputLength: 1600000,
    estimatedOutputLength: 3200,
    overview: "Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["gemini-10-pro"],
    name: modelNames[ModelFamily["gemini-10-pro"]],
    accuracy: 1.5,
    speed: 3,
    tokenConsumption: 0.2,
    estimatedInputLength: 25000,
    estimatedOutputLength: 3200,
    overview: "Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["gemini-15-flash"],
    name: modelNames[ModelFamily["gemini-15-flash"]],
    accuracy: 2,
    speed: 3,
    tokenConsumption: 0.2,
    estimatedInputLength: 800000,
    estimatedOutputLength: 3200,
    overview: "Google Cloudの利用が必須。",
  },
  {
    id: ModelFamily["gemini-20-flash"],
    name: modelNames[ModelFamily["gemini-20-flash"]],
    accuracy: 2.5,
    speed: 3,
    tokenConsumption: 0.2,
    estimatedInputLength: 800000,
    estimatedOutputLength: 3200,
    overview: "海外リージョン、Google Cloudの利用が必須。",
    tooltip: "試験運用版プレビューとなっております。",
  },
  {
    id: Text2ImageModelFamily["dall-e-3"],
    name: modelNames[Text2ImageModelFamily["dall-e-3"]],
    accuracy: null,
    speed: null,
    tokenConsumption: "3000/画像",
    estimatedInputLength: null,
    estimatedOutputLength: null,
    overview: "画像生成モデルです。回答生成モデルとして使用不可",
  },
];

export const LEGACY_MODEL_FAMILIES = [
  ModelFamily["gemini-10-pro"],
  ModelFamily["claude-3-opus"],
  ModelFamily["claude-3-sonnet"],
  ModelFamily["claude-3-haiku"],
];
