name: Release Drafter

on:
  pull_request:
    types: [closed]
    branches:
      - prod

permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'stg' && github.event.pull_request.base.ref == 'prod'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 #v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
