name: "Function: Check"

on:
  pull_request:
    paths:
      - "function/**"
      - ".github/workflows/lint-function.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: function

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Generate GitHub Access Token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.NEOLLM_INSTALLER_APP_ID }}
          private_key: ${{ secrets.NEOLLM_INSTALLER_PRIVATE_KEY }}

      - name: Install Python dependencies
        run: |
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Running lint
        run: make lint EXEC="poetry run"
